# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("marksapp", "0004_auto_20170409_1630")]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
