# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marksapp", "0005_auto_20170409_1652"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark", unique_together=set([("user", "url")])
        )
    ]
