# Generated by Django 2.0.4 on 2019-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksapp', '0012_auto_20181010_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='last_bumped',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last bumped'),
        ),
    ]
