from django.conf.urls import include, url
from django.conf.urls import url
from marksapp.misc import multitag_regex

from . import views

urlpatterns = [
    url(r'^$',
        views.index,
        name='index'),
    url(r'^add/$',
        views.add_mark,
        name='add_mark'),
    url(r'^mark/(?P<id>[0-9]+)/delete/$',
        views.delete_mark,
        name='delete_mark'),

    # api
    url(r'^api/mark/(?P<id>[0-9]+)/$',
        views.api_mark,
        name='api_mark'),
    url(r'^api/tags/(?P<prefix>[-\w\d+]+)$',
        views.api_tags,
        name='api_tags'),
    url(r'^api/tags/',
        views.api_tags,
        name='api_tags'),
    url(r'^api/get_title/$',
        views.api_get_title,
        name='api_get_title'),
    url(r'^api/delete_mark/(?P<id>[0-9]+)/$',
        views.api_delete_mark,
        name='api_delete_mark'),
    url(r'^api/delete_marks/$',
        views.api_delete_marks,
        name='api_delete_marks'),
    url(r'^api/edit_multiple/$',
        views.api_edit_multiple,
        name='api_edit_multiple'),
    url(r'^api/bump_mark/(?P<id>[0-9]+)/$',
        views.api_bump_mark,
        name='api_bump_mark'),
    url(r'^block/mark/(?P<id>[0-9]+)/$',
        views.edit_mark_form,
        name='edit_mark_form'),

    # user views
    url(r'^(?P<username>\w+)/mark/(?P<id>[0-9]+)/$',
        views.mark_permalink,
        name='mark_permalink'),
    url(r'^(?P<username>\w+)/tag/(?P<slug>{})/$'.format(multitag_regex[1:-1]),
        views.user_tag,
        name='user_tag'),
    url(r'^(?P<username>\w+)/tag/$',
        views.user_tag,
        name='user_tag'),
    url(r'^(?P<username>\w+)$',
        views.user_index,
        name='user_index'),
    url(r'^profile/$',
        views.user_profile,
        name='user_profile'),
    url(r'^import_netscape/$',
        views.import_netscape,
        name='import_netscape'),
    url(r'^import_json/$',
        views.import_json,
        name='import_json'),
    url(r'^export_json/$',
        views.export_json,
        name='export_json'),
    url(r'^changelog/$',
        views.changelog,
        name='changelog'),
    url(r'^register/$',
        views.register,
        name='register'),
    url(r'^guide/$',
        views.guide,
        name='guide'),
    url(r'^', include('django.contrib.auth.urls'),
        {'extra_context': {'page_title': 'login'}}),
]
