# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksapp', '0008_auto_20170414_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
